return {
	"nvimdev/dashboard-nvim",
	event = "VimEnter",
	dependencies = { "nvim-tree/nvim-web-devicons", lazy = true },
	opts = {
		theme = "doom",
		config = {
			header = {
				"                                   ",
				"                                   ",
				"   ⣴⣶⣤⡤⠦⣤⣀⣤⠆     ⣈⣭⣿⣶⣿⣦⣼⣆          ",
				"    ⠉⠻⢿⣿⠿⣿⣿⣶⣦⠤⠄⡠⢾⣿⣿⡿⠋⠉⠉⠻⣿⣿⡛⣦       ",
				"          ⠈⢿⣿⣟⠦ ⣾⣿⣿⣷    ⠻⠿⢿⣿⣧⣄     ",
				"           ⣸⣿⣿⢧ ⢻⠻⣿⣿⣷⣄⣀⠄⠢⣀⡀⠈⠙⠿⠄    ",
				"          ⢠⣿⣿⣿⠈    ⣻⣿⣿⣿⣿⣿⣿⣿⣛⣳⣤⣀⣀   ",
				"   ⢠⣧⣶⣥⡤⢄ ⣸⣿⣿⠘  ⢀⣴⣿⣿⡿⠛⣿⣿⣧⠈⢿⠿⠟⠛⠻⠿⠄  ",
				"  ⣰⣿⣿⠛⠻⣿⣿⡦⢹⣿⣷   ⢊⣿⣿⡏  ⢸⣿⣿⡇ ⢀⣠⣄⣾⠄   ",
				" ⣠⣿⠿⠛ ⢀⣿⣿⣷⠘⢿⣿⣦⡀ ⢸⢿⣿⣿⣄ ⣸⣿⣿⡇⣪⣿⡿⠿⣿⣷⡄  ",
				" ⠙⠃   ⣼⣿⡟  ⠈⠻⣿⣿⣦⣌⡇⠻⣿⣿⣷⣿⣿⣿ ⣿⣿⡇ ⠛⠻⢷⣄ ",
				"      ⢻⣿⣿⣄   ⠈⠻⣿⣿⣿⣷⣿⣿⣿⣿⣿⡟ ⠫⢿⣿⡆     ",
				"       ⠻⣿⣿⣿⣿⣶⣶⣾⣿⣿⣿⣿⣿⣿⣿⣿⡟⢀⣀⣤⣾⡿⠃     ",
				"                                   ",
				"                                   ",
			},
			center = {
				{
					icon = "  ",
					icon_hl = "Number",
					desc = "New file           ",
					desc_hl = "Number",
					key = "e",
					key_hl = "@string",
					key_format = " %s",
					action = "enew",
				},
				{
					icon = "󰈞  ",
					icon_hl = "Number",
					desc = "Find file           ",
					desc_hl = "Number",
					key = "s",
					key_hl = "@string",
					key_format = " %s",
					action = "Telescope find_files",
				},
				{
					icon = "  ",
					icon_hl = "Number",
					desc = "Recently opened files           ",
					desc_hl = "Number",
					key = "x",
					key_hl = "@string",
					key_format = " %s",
					action = "Telescope oldfiles",
				},
				{
					icon = "󰊄  ",
					icon_hl = "Number",
					desc = "Find word           ",
					desc_hl = "Number",
					key = "w",
					key_hl = "@string",
					key_format = " %s",
					action = "Telescope live_grep",
				},
				{
					icon = "󰉋  ",
					icon_hl = "Number",
					desc = "File explorer           ",
					desc_hl = "Number",
					key = "f",
					key_hl = "@string",
					key_format = " %s",
					action = "Telescope file_browser",
				},
				{
					icon = "󰊢  ",
					icon_hl = "Number",
					desc = "Git files           ",
					desc_hl = "Number",
					key = "g",
					key_hl = "@string",
					key_format = " %s",
					action = "Telescope git_files",
				},
				{
					icon = "󰒲  ",
					icon_hl = "Number",
					desc = "Lazy           ",
					desc_hl = "Number",
					key = "l",
					key_hl = "@string",
					key_format = " %s",
					action = "Lazy",
				},
			},
			footer = function()
				local lazy_stats = require("lazy.stats").stats()
				local ms = (math.floor(lazy_stats.startuptime * 100 + 0.5) / 100)
				return {
					" ",
					string.format("Loaded %d/%d plugins in %dms", lazy_stats.loaded, lazy_stats.count, ms),
				}
			end,
			vertical_center = true,
		},
	},
}
